version: "3.8"
services:
  app:
    build:
      args:
        user: nextlevelcourse
        uid: 1000
      context: ./
      dockerfile: dev.Dockerfile
    image: nextlevelcourse
    container_name: nextlevelcourse-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - nextlevelcourse-db-mysql
    networks:
      - nextlevelcourse

  nextlevelcourse-db-mysql:
    image: mysql:8.0
    container_name: nextlevelcourse-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: next_level_course
      MYSQL_ROOT_PASSWORD: MLtalBcE867g
      MYSQL_PASSWORD: MLtalBcE867g
      MYSQL_USER: next_level_course
      SERVICE_TAGS: development
      SERVICE_NAME: mysql
    volumes:
      - ./nlc-compose/mysql:/docker-entrypoint-initdb.d
      - ./nlc-compose/mysql/logs:/var/log/mysql
      - ./nlc-compose/mysql/data:/var/lib/mysql
    networks:
      - nextlevelcourse

  nginx:
    image: nginx:alpine
    container_name: nextlevelcourse-nginx
    restart: unless-stopped
    ports:
      - 8084:80
    volumes:
      - ./:/var/www
      - ./nlc-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nextlevelcourse
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nextlevelcourse-phpmyadmin
    ports:
        - 8085:80
    links:
        - nextlevelcourse
    restart: unless-stopped
    environment:
        PMA_HOST: nextlevelcourse-db-mysql
        PMA_USER: next_level_course
        PMA_PASSWORD: MLtalBcE867g
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    networks:
        - nextlevelcourse

networks:
  nextlevelcourse:
    driver: bridge