version: "1"
services:
  app:
    build:
      args:
        user: nextlevelcourse
        uid: 1000
      context: ./
      dockerfile: prod.Dockerfile
    image: nextlevelcourse
    container_name: nextlevelcourseproduction-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - nextlevelcourseproduction-db-mysql
    networks:
      - nextlevelcourseproduction

  nextlevelcourseproduction-db-mysql:
    image: mysql:8.0
    container_name: nextlevelcourseproduction-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prod_next_level_course
      MYSQL_ROOT_PASSWORD: MLtalBcE867g
      MYSQL_PASSWORD: MLtalBcE867g
      MYSQL_USER: next_level_course
      SERVICE_TAGS: production
      SERVICE_NAME: mysql
    volumes:
      - ./nlc-compose/mysql:/docker-entrypoint-initdb.d
      - ./nlc-compose/mysql/logs:/var/log/mysql
      - ./nlc-compose/mysql/data:/var/lib/mysql
    networks:
      - nextlevelcourseproduction

  nginx:
    image: nginx:alpine
    container_name: nextlevelcourseproduction-nginx
    restart: unless-stopped
    ports:
      - 8084:80
    volumes:
      - ./:/var/www
      - ./nlc-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nextlevelcourseproduction

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nextlevelcourseproduction-phpmyadmin
    ports:
      - 8085:80
    links:
      - nextlevelcourseproduction-db-mysql
    restart: unless-stopped
    environment:
      PMA_HOST: nextlevelcourseproduction-db-mysql
      PMA_USER: next_level_course
      PMA_PASSWORD: MLtalBcE867g
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - nextlevelcourseproduction

networks:
  nextlevelcourseproduction:
    driver: bridge
